ALTER TABLE Projects
    ADD IsArchived BIT NOT NULL DEFAULT 0;

ALTER TABLE Columns
    ADD IsArchived BIT NOT NULL DEFAULT 0;

ALTER TABLE Cards
    ADD IsArchived BIT NOT NULL DEFAULT 0;

ALTER TABLE Activity
    ADD IsArchived BIT NOT NULL DEFAULT 0;

ALTER TABLE Comments
    ADD IsArchived BIT NOT NULL DEFAULT 0;

ALTER TABLE States
    ADD IsArchived BIT NOT NULL DEFAULT 0;