ALTER TABLE Projects
    ADD ArchivedAt DATETIME DEFAULT NULL;

ALTER TABLE Columns
    ADD ArchivedAt DATETIME DEFAULT NULL;

ALTER TABLE Cards
    ADD ArchivedAt DATETIME DEFAULT NULL;

ALTER TABLE Activity
    ADD ArchivedAt DATETIME DEFAULT NULL;

ALTER TABLE Comments
    ADD ArchivedAt DATETIME DEFAULT NULL;

ALTER TABLE States
    ADD ArchivedAt DATETIME DEFAULT NULL;