CREATE TABLE [Users_Projects] (
    [UserId] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Users(Id),
    [ProjectId] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Projects(Id),
    [RoleId] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Roles(Id)
)