CREATE TABLE [States] (
    [Id] UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
    [Status] INT,
    [Priority] INT,
    [Row] INT NOT NULL,
    [Column] INT NOT NULL,
    [ProjectId] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Projects(Id),
    [CreatedAtUtc] DATETIME NOT NULL DEFAULT GETUTCDATE(),
    [CreatedBy] NVARCHAR(100) NOT NULL,
    [LastModifiedAtUtc] DATETIME DEFAULT NULL,
    [LastModifiedBy] NVARCHAR(100) DEFAULT NULL
)